version: "3.4"
services:
    website:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            APP_SERVICE: "website"
        volumes:
            - ".:/var/www"
            - "/var/www/.docker"
        depends_on:
            - mariadb
            - memcached
            - redis
    mariadb:
        image: "mariadb:10"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: "redis:alpine"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    memcached:
        image: "memcached:alpine"
        ports:
            - "11212:11211"
    adminer:
        image: adminer
        restart: always
        ports:
            - 1234:8080
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "${FORWARD_MAILHOG_PORT:-1026}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025"
